require("dotenv").config()
require("./db")
const CashierRoute = require("./routes/Cashier")
const RestaurantRoute = require("./routes/Restaurant")
const MenuItemRoute = require("./routes/Menu")
const OrderRoute = require("./routes/Orders")
const express = require("express")
const cors = require("cors")
const app = express()
app.use(express.json())
app.use(cors({origin: "http://localhost:5173" , credentials: true}))
app.use("/api",CashierRoute)
app.use("/api",RestaurantRoute)
app.use("/api",MenuItemRoute)
app.use("/api",OrderRoute)
app.listen(process.env.PORT,() => console.log("Server running on port: ",process.env.PORT))